
'use strict'; // http://www.w3schools.com/js/js_strict.asp


// web framework
var express = require('express');
var router = express.Router();


// forge config information, such as client ID and secret
var config = require('./config');


router.get('/step/generate', function (req, res) {
    console.log('Generate STEP file');
    console.log(req);
    var stepUrl = createStep({ componrnt: 'component1' })
    res.json({ stepUrl: stepUrl })

});


function createStep(jsonParams) {
    return "Step file URL generated by servet method call";
}

// module.exports = createStep;
module.exports = router;
