
'use strict'; // http://www.w3schools.com/js/js_strict.asp


// web framework
var express = require('express');
var router = express.Router();

var rdb = require('./rivetDatabase');

// forge config information, such as client ID and secret
var config = require('../server/config');//('./config');


router.get('/step/getrivets', function (req, res) {
    //console.log('Get rivets portfolio');
    //console.log(req);
    //rdb.getRivets(function(arg){res = arg;});
    //var rivetsJson = rdb.getRivets(function(arg){res = arg;});
    //console.log(rivetsJson);
    //res.json(rivetsJson)

    try {
        console.log('Start Get rivets portfolio');
       
        res.json({ id: '1', number: '1111', description: 'Nyt 1' });

        console.log('End Get rivets portfolio');
    }
    catch (err) {
        res.status(500).end(err);
    }


});


// function getRivets(jsonParams) {
//     return "Step file URL generated by servet method call";
// }

// module.exports = createStep;
module.exports = router;
